// READ ME FIRST
// THE REGISTER SETTINGS PROVIDED BELOW ARE GIVEN BY AXIGN BV TO THE
// CUSTOMER ON A BEST EFFORT BASIS AND SHOULD ONLY BE TREATED AS AXIGN’S
// ADVICE TO THE CUSTOMER HOW TO PROGRAM AXIGN’S PRODUCT IN ORDER TO BEST
// ACHIEVE THE DESIRED SPECIFICATIONS.
// IT IS THE CUSTOMER’S SOLE RESPONSIBILITY TO DECIDE WHAT VALUES WILL BE
// WRITTEN IN WHICH REGISTERS WHEN USING AXIGN’S PRODUCT IN THE CUSTOMER’S
// FINAL APPLICATION.
// IN NO EVENT SHALL AXIGN BV BE LIABLE FOR ANY SPECIAL, INCIDENTAL,
// CONSEQUENTIAL, LOSS OF PROFITS OR OTHER INDIRECT DAMAGES OF ANY KIND, OR
// FOR EXEMPLARY OR PUNITIVE DAMAGES OF ANY KIND, WHETHER OR NOT THE
// CUSTOMER WAS ADVISED OF OR COULD FORESEE THE POSSIBILITY OF SUCH DAMAGES.
// NOR SHALL AXIGN BV BE LIABLE FOR ANY INJURY, LOSS OR DAMAGE, INCLUDING
// LOSS OF USE OR DESTRUCTION OF ANY PROPERTY, HOWSOEVER ARISING, THAT
// MAY BE SUSTAINED BY CUSTOMER OR BY ANY OTHER PERSON AS A RESULT OF OR
// IN CONNECTION WITH THE USE OF THE REGISTER SETTINGS.


// Array of register write commands to send to the AX5689
// Settings for AX5689 Reference Design 4 x MP1916, 8 x GaNFET
// Audio input format: I2S 2 channels 192 kHz sample rate 
// 2 x BTL, output filter: L = 4.7 uH, C = 2.2 uF
// ADC input resistors: 10000 Ohm (0.1 %)
// PVDD = 50
// Date: 2025/01/09 15:04:04
#include <stdint.h>
extern const uint16_t amplifierCommands[];
#define REG01_VALUE 0xFFFF
#define REG01_VALUE_DEFAULT 0xFF00
#define REG02_PSTART_DISABLE 0x17FF
#define REG02_PSTART_ENABLE 0x1FFF
#define REG03_VALUE 0x0055
#define REG03_VALUE_CM50 0x1155
#define REG03_VALUE_DEFAULT 0x0000
#define REG07_VALUE 0x0001
#define REG07_VALUE_DEFAULT 0x0064
#define REG56_VALUE 0x0C34
#define REG56_RESET_VALUE 0x0434


extern float PVDD ;
extern uint32_t SAMPLE_RATE;
extern float UVP;
extern float OVP;
extern uint16_t VolumeHex;
